export const articleBatchQualityPolicy = {
  qualityPolicyId: "article-batch-quality-policy",
  policyVersion: "1.0.0",
  mode: "strict_production",
  stageOrder: [
    "INPUT_READING",
    "SEMANTIC_PROVIDER_PREFLIGHT",
    "SCRIPT_GENERATION",
    "SCRIPT_QA",
    "VISIBLE_COPY_AND_VISUAL_PLAN",
    "PREVIEW_RENDER",
    "MEDIA_TOOLCHAIN_PREFLIGHT",
    "PREVIEW_QA",
    "FINAL_RENDER",
    "OUTPUT_QA",
    "FINAL_DELIVERY",
  ],
  stageStatuses: ["pending", "running", "passed", "repairing", "blocked", "rejected", "skipped"],
  retryPolicy: {
    maxInputReadAttempts: 2,
    maxScriptRepairAttempts: 2,
    maxPreviewAttempts: 2,
    maxRerenderOutputAttempts: 1,
    maxRenderAttempts: 2,
  },
  semanticReview: {
    requiredInStrictProduction: true,
    providerRequired: true,
    responseSchemaRequired: true,
    maxRepairAttempts: 2,
    failClosedWhenUnavailable: true,
    failClosedWhenResponseInvalid: true,
  },
  scriptRepair: {
    enabled: true,
    maxAttempts: 2,
    preserveEvidence: true,
    preserveDataDisplayRequirements: true,
    blockedCategories: ["UNSUPPORTED_CLAIM", "EVIDENCE_TRACEABILITY", "CONTRADICTORY_SOURCE", "INPUT_INTEGRITY"],
    autoRepairableCategories: [
      "COPY_DUPLICATION",
      "ROLE_REDUNDANCY",
      "NARRATIVE_LOGIC",
      "SCRIPT_EVIDENCE_ALIGNMENT",
      "SCRIPT_DATA_DISPLAY_OMISSION",
      "GENERIC_SUMMARY",
      "DATA_DISPLAY_OMISSION",
      "INCOMPLETE_COPY",
      "TEXT_CAPACITY",
    ],
  },
  repairPolicy: {
    routeByCategory: {
      INPUT_MISSING_OR_PARSE_FAILED: "re_read_input",
      INPUT_INTEGRITY: "re_read_input",
      HTML_PARSE_FAILED: "re_read_input",
      TABLE_READ_FAILED: "re_read_input",
      EVIDENCE_MISSING: "repair_script",
      UNSUPPORTED_NUMBER: "repair_script",
      CONTENT_DUPLICATION: "repair_script",
      NARRATIVE_ORDER: "repair_script",
      TABLE_OR_DATA_VISUALIZATION_OMISSION: "repair_script",
      SCRIPT_EVIDENCE_ALIGNMENT: "repair_script",
      SCRIPT_DATA_DISPLAY_OMISSION: "repair_script",
      VISIBLE_COPY_OVERFLOW: "repair_visible_copy",
      VISIBLE_COPY_INCOMPLETE: "repair_visible_copy",
      VISIBLE_COPY_ELLIPSIS: "repair_visible_copy",
      VISIBLE_COPY_PLACEHOLDER: "repair_visible_copy",
      VISIBLE_COPY_CAPACITY: "repair_visible_copy",
      VISIBLE_COPY_LAYOUT_BINDING: "repair_visible_copy",
      SHOT_SELECTION: "replan_visual",
      MOTION: "replan_visual",
      TRANSITION: "replan_visual",
      LAYOUT_VISUAL: "replan_visual",
      SHOT_CAPACITY_MISMATCH: "replan_visual",
      SCRIPT_FACT_OR_LOGIC_ISSUE: "repair_script",
      LAYOUT_OR_TYPOGRAPHY_ISSUE: "repair_visible_copy",
      SHOT_REPETITION: "replan_visual",
      MOTION_OR_TRANSITION_ISSUE: "replan_visual",
      RENDER_ENCODING_OR_OUTPUT_PARAMETER_ISSUE: "rerender_output",
      SEMANTIC_REVIEW_UNAVAILABLE: "manual_review",
      SEMANTIC_PROVIDER_PREFLIGHT_FAILED: "provider_configuration",
      MEDIA_TOOLCHAIN_UNAVAILABLE: "toolchain_configuration",
    },
    maxRepairAttemptsPerIssue: 2,
    forbiddenScriptRepairChanges: [
      "invent_new_numbers_or_conclusions",
      "drop_required_evidence",
      "drop_required_data_display_plan",
      "convert_recommendation_to_fact",
      "insert_demo_copy",
      "insert_ellipsis",
    ],
  },
  finalDeliveryPolicy: {
    requireAllStagesPassed: true,
    blockOnPreviewOrOutputBlocker: true,
    requireTraceableInputSnapshot: true,
    requireTraceableScriptAttempt: true,
    requireTraceableRenderAttempt: true,
  },
} as const;

export type ArticleBatchStage = (typeof articleBatchQualityPolicy.stageOrder)[number];
export type ArticleBatchStageStatus = (typeof articleBatchQualityPolicy.stageStatuses)[number];
export type ArticleBatchRepairRoute = (typeof articleBatchQualityPolicy.repairPolicy.routeByCategory)[keyof typeof articleBatchQualityPolicy.repairPolicy.routeByCategory];
